version: '3'

services:
  mongo-auth-container:
    image: mongo
    ports:
      - "2700:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local